### ISSUE TITLE
Why does SwiftTor not work on macOS?

### ISSUE THREAD

**Issue by psalzAppDev** [FlorianHubl/SwiftTor#1]
Hi, I tried to run the sample SwiftUI code on Mac, and Tor will not connect. You also mention that SwiftTor is only available for iOS. I wonder why that is? Are there any limitations on macOS for the connections?

Thanks,
Peter

**Comment by FlorianHubl** [comment]
I just haven't been able to get the Tor.framework to run on macOS yet. In theory it should still work. When I try it the logs says:
Opening Socks listener on 127.0.0.1:19050
Opening DNS listener on 127.0.0.1:12345

 It appears that macOS does not allow Tor to open the Socks and DNS listener.

**Comment by FlorianHubl** [comment]
Oh you have to allow Incoming Connections (Server). But now I have this problem: Problem bootstrapping. Stuck at 0% (starting): Starting. (Operation not permitted; MISC; count 13
<img width="641" alt="Bildschirmfoto 2024-02-28 um 23 50 46" src="https://github.com/FlorianHubl/SwiftTor/assets/49409175/7a94a952-a901-4766-adcc-ede41580b97c">

**Comment by FlorianHubl** [comment]
Oh wow. It is simple. Just also activate Outgoing Connections. The Tor Framework has to do outgoing connections to Bootstrap. SwiftTor works on macOS.
<img width="636" alt="Bildschirmfoto 2024-02-28 um 23 52 41" src="https://github.com/FlorianHubl/SwiftTor/assets/49409175/0b73de1a-8314-44f4-bc0b-129eceee077f">

**Comment by psalzAppDev** [comment]
Oh that's great, I assumed it was something like this and wanted to investigate, but you were much faster :) Thank's a lot!

Do you think SwiftTor is production-ready, or will Apple object to the fact that Tor is part of an app?

**Comment by FlorianHubl** [comment]
There are many apps in the iOS App Store which are using Tor. So I guess Apple should allow macOS Apps which are using Tor. SwiftTor is relatively new. I would suggest testing Swift Tour extensively before using it in production. I have already tested SwiftTor a lot and have not encountered any issues.

**Comment by psalzAppDev** [comment]
> There are many apps in the iOS App Store which are using Tor. So I guess Apple should allow macOS Apps which are using Tor. SwiftTor is relatively new. I would suggest testing Swift Tour extensively before using it in production. I have already tested SwiftTor a lot and have not encountered any issues.

Thanks a lot!
